version: '3.8'
services:
  api:
    depends_on:
      - postgres
    build: ./api
    container_name: api_backend
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
  postgres:
    image: ankane/pgvector
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: