version: '3.8'
services:
  api:
    depends_on:
      - postgresdb
    build: ./api
    container_name: api_backend
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
  postgresdb:
    container_name: local-postgres
    image: postgres
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
volumes:
  db: